### PR TITLE
Use Skim instead of TeXShop

### PR DESCRIPTION
**Pull request by redpanda1234**
Changed default .pdf viewer for TeX to  Skim instead of TeXShop.

### CODE REVIEW

**Comment by redpanda1234** [comment]
Update: apparently, skim also doesn't autorefresh the .pdf --- at least, not the way it's currently configured.

**Comment by raxod502** [comment]
That's unfortunate. We'll definitely need to make sure that Skim can be configured for feature parity with TeXShop before switching over.

**Comment by redpanda1234** [comment]
Hold on --- TeXshop wasn't autoupdating for me before switching either.  Was it supposed to?

**Comment by redpanda1234** [comment]
Aha.  I should have known -- I'll try it out.

**Comment by raxod502** [comment]
You'll want to rebase this on the most recent `develop` branch at some point.

**Comment by raxod502** [comment]
This issue is being closed automatically since it has a "waiting on response" label but hasn't had any activity in 90 days. But don't worry: if you have some information to help move the discussion along, just leave a comment and I'll re-open the issue.

*(Comment generated automatically by [NO CARRIER](https://github.com/twbs/no-carrier) via [tidier](https://github.com/raxod502/tidier).)*

**Pull request closed without merging**
